### PR TITLE
Add getProject function

### PR DESCRIPTION
**Pull request by d4rkr00t**

### CODE REVIEW

**Comment by thejameskyle** [comment]
I think a `getProject` function that matches [`getWorkspaces`](https://github.com/boltpkg/bolt/blob/master/src/functions/getWorkspaces.js#L9-L13) would probably be better,

**Comment by d4rkr00t** [comment]
Yeah, i can rename

**Comment by thejameskyle** [comment]
Sorry, I wanted it both renamed and to return an object with `dir` `name` and `config` like `getWorkspaces` https://github.com/boltpkg/bolt/blob/master/src/functions/getWorkspaces.js#L9-L13

**Comment by d4rkr00t** [comment]
Updated!

**Comment by thejameskyle** [comment]
I changed the interface to be:

```js
bolt.getProject({ cwd: '/../' });
```

Where `cwd` defaults to `process.cwd()` like the other functions.

**Pull request merged**
