### PR TITLE
Add bolt_config_user_agent env var to `yarn add`

### PR DESCRIPTION
**Pull request by Blasz**
Follows on from #198 which added this to the install command. This
should also be added to at least the add command as preinstall yarn
scripts are ran for both install and add.

### CODE REVIEW

**Comment by lukebatchelor** [comment]
Apologies for letting this one slip through @Blasz .

LGTM. Only thought is, is there anyway we could make this just always be set whenever we run anything through spawn?  Or am I just missing some context here and this particular case is special?

Give me a shout and I'll merge.

**Comment by Blasz** [comment]
@lukebatchelor Yeah we could probably do that, nothing special about this particular case that I'm aware of. I don't have a ton of context surrounding this either.

I'll implement it sometime soon.

**Comment by Blasz** [comment]
@lukebatchelor I've updated the implementation to add the user agent vars to all yarn commands. We spawn some other non-yarn commands so I didn't want to add it to all spawn calls, I think yarn is a decent trade-off.
Let me know what you think.

**Comment by lukebatchelor** [comment]
Yup, completely agree.

**Comment by lukebatchelor** [comment]
Released in 0.24.2 🎉

**Pull request merged**
